import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/header"

/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

// Metadata (SEO) global
export const metadata: Metadata = {
  title: "Aula Next.js",
  description: "Aprendendo do zero com Next.js",
  openGraph: {
    title: "Aula Next.js",
    description: "Aprendendo do zero com Next.js",
    images: ['https://sujeitoprogramador.com/steve.png']
  },
  robots: {
    index: true,
    follow: true,
    nocache: false
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
      <body
        className="antialiased bg-gray-100"
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
